### ISSUE TITLE
Sonar Qualitygates plugin doesn't show the correct status on immediate run

### ISSUE THREAD

**Issue by akshaydewan** [Haufe-Lexware/gocd-plugins#1]
We tried integrating the sonar-qualitygates-plugin with our app and found that it wasn't showing the correct status of the quality gate after running. On subsequent runs, it started showing the correct result.

We think that it may be because the sonar server was still processing the result while the plugin queried the server. We see the following message from sonar after the run:

```
Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report.
```

Also, this [documentation](http://docs.sonarqube.org/display/SONAR/Breaking+the+CI+Build) indicates that we must poll the sonar server for the status before we check the quality gates.

**Comment by markus2810** [comment]
Thank you for the feedback.
We are using the plugin not directly behind executing the sonar scan. In our case the quality gate result is requested some minutes after the scan.
Do you execute the sonar scan in the same pipeline, stage or job in that you run the scan? Would your issue be solved, if the plugin would be extended like follow: 
1. scan result must not be older than the start of the pipeline run
2. poll for a new result with a definable timeout e.g. 5 minutes and fail if there is no new result in that time frame

Kind Regards,
Markus

**Comment by akshaydewan** [comment]
Hi Markus,

We've set up the plugin to run as a Task immediately after we run the Sonar scan task (in the same Job).

The solution you've suggested sounds good. I think it would solve the problem.

Thanks!

**Comment by akshaydewan** [comment]
Hi,

I've been dabbling with this in my free time. Do you have any guidelines for contributing?

Right now, I'm facing a few issues with the build:
- The project doesn't compile. I modified the go-plugin-api jar file to be fetched from maven instead of a local jar. (This is currently on my fork).
- Once I got it to compile, I'm seeing the following unit tests failing:

```
Failed tests: 
  JobPropParamParserTest.testOnePropVarInParameter:57 expected:<[Test Value ]1> but was:<[test_property_]1>
  JobPropParamParserTest.testEnvVarAsPropVarNameInParameter:90 expected:<[Test Value ]1TestPluginStage> but was:<[test_property_]1TestPluginStage>
  JobPropParamParserTest.testPropVarAndEnvVarInParameter:79 expected:<[Test Value 3]> but was:<[test_property_TestPluginStage]>
  JobPropParamParserTest.testTwoPropVarsInParameter:67 expected:<[Test Value 1Test Value ]2> but was:<[test_property_1test_property_]2>
```

Any idea around these failing tests?

Also, the package structure starting with `com.tw` is confusing. Shouldn't your packages start with `com.haufe-lexware.`?

Thanks!

**Comment by markus2810** [comment]
Hi,

we do not have contribution guidelines yet. For submitting a change, please send a pull request. As code quality check, we run sonaqube. Have a look at http://bob.xeam-solutions.com for current issues.

for running these tests, you need an test pipeline where the unit tests can read pipeline properties.

![image](https://cloud.githubusercontent.com/assets/2051899/13049849/01874c5c-d3f0-11e5-88d9-32ae706338ea.png)

Sure, the namespace should start as you suggested. We started developing the plugins with the com.tw namespace and did not renamed them yet.

We appreciate your contribution

Thanks!

**Comment by akshaydewan** [comment]
Great! Thanks a lot for the info!

**Comment by markus2810** [comment]
Are you working on fixing this issue? If not we will start to implement this. 
Thanks!

**Comment by akshaydewan** [comment]
Unfortunately, I haven't been able to pick this up. You guys can go ahead and fix it.
Thanks!

**Comment by bradeac** [comment]
Hello, 

I have tried to fix this issue, although I could not replicate this problem on my machine.

I pushed the changes and also an updated .jar which includes the changes. Please inform us if the changes are fixing your issue or not.

Thank you !
