### ISSUE TITLE
Support for user auth

### ISSUE THREAD

**Issue by sanchitbahal** [Haufe-Lexware/gocd-plugins#12]
Does the plugin have support for accepting user credentials if the Sonar server needs authentication? I could not locate an option for the same in settings.

**Comment by mpaivafontes** [comment]
It's done in the master branch but it looks broken.

SonarTaskExecutor:126

**Comment by droberin** [comment]
I comprehend that the needed env variables to set at the GoCD's Pipeline are:
GO_BUILD_USER
GO_BUILD_USER_PASSWORD

Yet, It gets an unauthorised error (401).
Is there any change that someone can fix this code and do a pull request?

I'm afraid I'm not a Java dev.

Thanks, mates.

**Comment by droberin** [comment]
Seems like it doesn't authenticate to get the quality gate before authenticate to request the analysis. I managed to make it authenticate by modifying some code.

I didn't get it to properly work anyway. My Sonarqube server reports last analysis was prior to the time I run this pipeline.

Any help?

**Comment by markus2810** [comment]
The plugin expects, that the sonar scan was done in the same pipeline.
Did you push results to sonar server in a previous job or stage?

**Comment by droberin** [comment]
I think I understood this plugin wrong. Thanks, @markus2810 .

I left a [pull-request](https://github.com/Haufe-Lexware/gocd-plugins/pull/15) that I think will fix the problem of authentication while obtaining Project's Quality Gate. Hope it's alright.

**Comment by markus2810** [comment]
Thanks. We will review and integrate it

**Comment by bradeac** [comment]
Hello droberin,

Your code works as expected. Thanks for the pull request :)
