### ISSUE TITLE
docker-pipeline-plugin

### ISSUE THREAD

**Issue by marufaytekin** [Haufe-Lexware/gocd-plugins#3]
Does docker-pipeline plugin require docker machine installation on goad-agent?

**Comment by bradeac** [comment]
Hello.

No, you don't need to install docker machine on your agent, docker engine is enough.

Feel free to ask if you have anymore questions.
Have a nice day !

**Comment by marufaytekin** [comment]
Thanks for your effort. We successfully created a docker image build and push task in the pipeline with docker-pipeline-plugin.

Regards.
